### ISSUE TITLE
is this needed after rollup-plugin-commonjs is supporting dynamic requires

### ISSUE THREAD

**Issue by ashubham** [PepsRyuu/rollup-plugin-commonjs-alternate#2]
According to this 
https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md#v1110

`plugin-commonjs` should support dynamic `require` statements. Do we still need to use this alternate ?

**Comment by PepsRyuu** [comment]
For HMR engines like ```react-refresh```, seems like you can get away without it, but not because of anything that the plugin changed, but because the ```rollup-plugin-react-refresh``` plugin I wrote works by adding ```require()``` calls during bundle generation, not during bundle build which is when ```commonjs``` detects dynamic requires and modifies them.

You will still need to specify ```namedExports``` in the meantime though, but with this plugin you don't have to. The official plugin will eventually have the same support but it's not there at the moment for some reason.

If using ```react-hot-loader```, it's still necessary to use this plugin. There's still some conflicting design principles that haven't been resolved:

* It will not allow require to be inside ESM modules. This causes the build to break still because it wraps the entire module in a function, which consequently wraps import statements inside a function which is invalid syntax.

* They have a different meaning of dynamic requires, and require you to whitelist them in the plugin options. This is fundamentally incompatible for HMR engines that depend have code like ```require(module.id)```. That's what I mean by dynamic requires, ones where you don't know what you're requiring at all. 

Hope this helps!

**Comment by ashubham** [comment]
Cool, thanks that helps.
